[project]
name = "cli-library-lending-manager"
version = "0.1.0"
description = "Persistent keyboard-driven terminal library lending manager"
authors = [
    { name = "Shaheer Ahmed", email = "sherrymaster2@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "readchar>=4.2.2,<5",
]

[project.scripts]
cli-library-lending-manager = "cli_library_lending_manager.presentation.cli:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
